"""
compare_runs.py — paired bootstrap between every pair of finished runs.

Comparisons are restricted to the folds both runs actually completed, and the fold set used
is printed with every result. E07 was killed at the wall clock after 4 of 5 folds, so any
comparison involving it covers folds 0-3 only and says so; nothing is extrapolated to the
missing fold.

Every difference is resampled over GROUPS, not rows, and reported with its interval. A
difference whose interval contains zero is printed as indistinguishable and must be reported
that way (PROTOCOL.md §4).

Usage:
    python src/compare_runs.py --datasets <root> [--runs E05 E06 E07 E08 E09]
"""
from __future__ import annotations
import argparse, glob, itertools, json, os, sys
import numpy as np
import torch

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import corpora
import metrics as M
from model import decode, N_DR, N_DME


def load_run(run):
    """{fold: (uids, dr_logits, dme_logits)} for every archived out-of-fold file."""
    out = {}
    for p in sorted(glob.glob(os.path.join("runs", run, "oof_*.npz"))):
        f = int(os.path.basename(p).split("_")[1].split(".")[0])
        z = np.load(p, allow_pickle=True)
        out[f] = ([str(u) for u in z["uids"]],
                  torch.from_numpy(z["dr_logits"]), torch.from_numpy(z["dme_logits"]))
    return out


def completed_folds(run):
    """Folds with metrics in results.json — a run killed mid-fold leaves an oof file for a
    fold it never finished, and that fold must not enter a comparison."""
    rj = os.path.join("runs", run, "results.json")
    if not os.path.exists(rj):
        return set()
    try:
        j = json.load(open(rj))
    except Exception:
        return set()
    if "run_id" not in j:
        return set()
    return {f["fold"] for f in j.get("folds", []) if f.get("metrics")}


def stack(data, folds, uid_order=None):
    uids, dr, dme = [], [], []
    for f in sorted(folds):
        u, d, m = data[f]
        uids += u; dr.append(d); dme.append(m)
    dr, dme = torch.cat(dr), torch.cat(dme)
    if uid_order is not None:
        pos = {u: i for i, u in enumerate(uids)}
        idx = np.array([pos[u] for u in uid_order])
        return uid_order, dr[idx], dme[idx]
    return uids, dr, dme


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--datasets", nargs="+", required=True)
    ap.add_argument("--runs", nargs="+",
                    default=["E05", "E06", "E07", "E08", "E09"])
    ap.add_argument("--out", default="docs/generated/comparisons.md")
    ap.add_argument("--boot", type=int, default=2000)
    a = ap.parse_args()

    rows = corpora.build(a.datasets, ("IDRiD", "Messidor-2"))
    by = {r["uid"]: r for r in rows}
    split = json.load(open("data/splits/dev_v1.json"))

    runs = {}
    for r in a.runs:
        d, cf = load_run(r), completed_folds(r)
        if d and cf:
            runs[r] = (d, cf & set(d))
            print(f"  {r}: folds {sorted(runs[r][1])}")
        else:
            print(f"  {r}: no usable out-of-fold data, skipped")

    lines = ["# Paired comparisons between runs", "",
             "Generated by `src/compare_runs.py`. Every difference is a paired bootstrap "
             "over groups, restricted to the folds **both** runs completed. An interval "
             "containing zero means the two runs are indistinguishable on that metric.", ""]
    lines.append("| A | B | folds | n | metric | A − B | 95 % interval | verdict |")
    lines.append("|---|---|---|---|---|---|---|---|")

    for ra, rb in itertools.combinations(runs, 2):
        (da, fa), (db, fb) = runs[ra], runs[rb]
        shared = sorted(fa & fb)
        if not shared:
            continue
        uids, dra, dmea = stack(da, shared)
        _, drb, dmeb = stack(db, shared, uid_order=uids)
        sub = [by[u] for u in uids]
        g = np.array([split["groups"][u] for u in uids])
        y_dr = np.array([r["dr"] for r in sub])
        three = np.array([r.get("dme_label_space") == "3class" and r["dme"] is not None
                          for r in sub])
        y_dme = np.array([r["dme"] if r["dme"] is not None else -1 for r in sub])

        for head, y, la, lb, k, mask in (
                ("DR", y_dr, dra, drb, N_DR, np.ones(len(sub), bool)),
                ("DME", y_dme, dmea, dmeb, N_DME, three)):
            pa_, pb_ = decode(la, k, "ordinal").numpy(), decode(lb, k, "ordinal").numpy()
            for mname, fn, sc, fmt in (
                    ("accuracy", M.accuracy, 100, "{:+.2f} pts"),
                    ("QWK", lambda t, p: M.quadratic_weighted_kappa(t, p, k), 1, "{:+.3f}")):
                d, lo, hi, sig = M.paired_bootstrap_diff(
                    y[mask], pa_[mask], pb_[mask], fn, g[mask], n_boot=a.boot)
                verdict = "**significant**" if sig else "indistinguishable"
                lines.append(
                    f"| {ra} | {rb} | {','.join(map(str, shared))} | {int(mask.sum())} | "
                    f"{head} {mname} | {fmt.format(d * sc)} | "
                    f"[{fmt.format(lo * sc)}, {fmt.format(hi * sc)}] | {verdict} |")
        print(f"  compared {ra} vs {rb} on folds {shared}")

    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    open(a.out, "w").write("\n".join(lines) + "\n")
    print(f"\nwrote {a.out}  ({len(lines) - 5} comparisons)")


if __name__ == "__main__":
    main()
